[package]
name = "gtk-queries"
version = "0.1.0"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"

[dependencies]
gtk = "0.8.0"
gio = "0.8.0"
glib = "0.9.1"
gdk = "0.12.0"
regex = "1"
tables = { path = "../tables" }
postgres = { version="0.17.1", features = [ "with-chrono-0_4" ] }
# csv = "1.1.1"
sourceview = "0.8.0"
nlearn = { path="../nlearn" }
libloading = "0.5"
rusqlite = "0.21.0"

[[bin]]
name="queries"
path="src/main.rs"

[lib]
name="gtk_queries"
path="src/lib.rs"


