[package]
name = "gtk-queries"
version = "0.1.0"
authors = ["Diego Lima <lima.ds@outlook.com>"]
edition = "2018"

[dependencies]
gtk = "0.7.0"
gio = "0.7.0"
glib = "0.8.0"
regex = "1"
tables = { path = "../tables" }
postgres = "0.15.1"
# csv = "1.1.1"
sourceview = "0.7.0"
gdk="0.11.0"
